### ISSUE TITLE
你好，我使用你的源码编译10至尊的内核，最后只生成了Image和dtbo.img

### ISSUE THREAD

**Issue by djhdj1** [CoolestEnoch/kernel-su-xiaomi-cas#2]
你好，我使用你的源码编译10至尊的内核，最后只生成了Image和dtbo.img，正常的话是不是应该还有Image.gz和Image.gz-dtb？我应该如何让这两个文件也编译出来？感谢大佬!

**Comment by CoolestEnoch** [comment]
我的话就只替换了一个Image然后开机，ksu是正常的😂
